// <auto-generated />
using System;
using Financeiro.Infra.Data.Context;
using FirebirdSql.EntityFrameworkCore.Firebird.Metadata;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Financeiro.Infra.Data.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260923000647_initialMigration")]
    partial class initialMigration
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Fb:ValueGenerationStrategy", FbValueGenerationStrategy.IdentityColumn)
                .HasAnnotation("ProductVersion", "10.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 31);

            modelBuilder.Entity("Financeiro.Domain.Entities.Cliente", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasAnnotation("Fb:ValueGenerationStrategy", FbValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Cpf")
                        .IsRequired()
                        .HasMaxLength(14)
                        .HasColumnType("VARCHAR(14)");

                    b.Property<DateTime>("DataCadastro")
                        .HasColumnType("TIMESTAMP")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("VARCHAR(200)");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("VARCHAR(200)");

                    b.Property<string>("Telefone")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("VARCHAR(20)");

                    b.HasKey("Id");

                    b.ToTable("Cliente");
                });

            modelBuilder.Entity("Financeiro.Domain.Entities.Pagamento", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasAnnotation("Fb:ValueGenerationStrategy", FbValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime?>("CompletedAt")
                        .HasColumnType("TIMESTAMP");

                    b.Property<DateTime>("CriadoEm")
                        .HasColumnType("TIMESTAMP")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<short>("Status")
                        .HasColumnType("SMALLINT")
                        .HasDefaultValue((short)0);

                    b.Property<string>("TransacaoId")
                        .IsRequired()
                        .HasColumnType("BLOB SUB_TYPE TEXT");

                    b.Property<short>("Type")
                        .HasColumnType("SMALLINT")
                        .HasDefaultValue((short)0);

                    b.Property<decimal>("Valor")
                        .HasPrecision(18, 2)
                        .HasColumnType("DECIMAL(18,2)");

                    b.Property<int>("VendaId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("Status")
                        .HasDatabaseName("IDX_PAGAMENTO_STATUS");

                    b.HasIndex("VendaId")
                        .HasDatabaseName("IDX_PAGAMENTO_VENDA");

                    b.ToTable("Pagamento", t =>
                        {
                            t.HasCheckConstraint("CK_PAGAMENTO_STATUS", "STATUS BETWEEN 0 AND 2");

                            t.HasCheckConstraint("CK_PAGAMENTO_TIPO", "TIPO_PAGAMENTO BETWEEN 0 AND 3");
                        });
                });

            modelBuilder.Entity("Financeiro.Domain.Entities.Produto", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasAnnotation("Fb:ValueGenerationStrategy", FbValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("VARCHAR(200)");

                    b.Property<decimal>("Preco")
                        .HasPrecision(18, 4)
                        .HasColumnType("DECIMAL(18,2)")
                        .HasDefaultValue(0m);

                    b.Property<int>("QuantidadeEstoque")
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(0);

                    b.HasKey("Id");

                    b.HasIndex("Nome")
                        .HasDatabaseName("IDX_PRODUTO_NOME");

                    b.ToTable("Produto");
                });

            modelBuilder.Entity("Financeiro.Domain.Entities.Venda", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasAnnotation("Fb:ValueGenerationStrategy", FbValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("ClienteId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CriadoEm")
                        .HasColumnType("TIMESTAMP")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<DateTime?>("PagoEm")
                        .HasColumnType("TIMESTAMP");

                    b.Property<short>("Status")
                        .HasColumnType("SMALLINT")
                        .HasDefaultValue((short)0);

                    b.Property<decimal>("Total")
                        .HasPrecision(18, 2)
                        .HasColumnType("DECIMAL(18,2)")
                        .HasDefaultValue(0m);

                    b.HasKey("Id");

                    b.HasIndex("ClienteId")
                        .HasDatabaseName("IDX_VENDA_CLIENTE");

                    b.HasIndex("Status")
                        .HasDatabaseName("IDX_VENDA_STATUS");

                    b.ToTable("Venda", t =>
                        {
                            t.HasCheckConstraint("CK_VENDA_STATUS", "STATUS BETWEEN 0 AND 3");
                        });
                });

            modelBuilder.Entity("Financeiro.Domain.Entities.VendaItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasAnnotation("Fb:ValueGenerationStrategy", FbValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("ProdutoId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Quantidade")
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(1);

                    b.Property<decimal>("ValorTotal")
                        .HasPrecision(18, 4)
                        .HasColumnType("DECIMAL(18,2)")
                        .HasDefaultValue(0m);

                    b.Property<decimal>("ValorUnitario")
                        .HasPrecision(18, 4)
                        .HasColumnType("DECIMAL(18,2)")
                        .HasDefaultValue(0m);

                    b.Property<int>("VendaId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("ProdutoId")
                        .HasDatabaseName("IDX_VENDAITEM_PRODUTO");

                    b.HasIndex("VendaId")
                        .HasDatabaseName("IDX_VENDAITEM_VENDA");

                    b.ToTable("VendaItem");
                });

            modelBuilder.Entity("Financeiro.Domain.Entities.Pagamento", b =>
                {
                    b.HasOne("Financeiro.Domain.Entities.Venda", "Venda")
                        .WithMany("Pagamentos")
                        .HasForeignKey("VendaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Venda");
                });

            modelBuilder.Entity("Financeiro.Domain.Entities.Venda", b =>
                {
                    b.HasOne("Financeiro.Domain.Entities.Cliente", "Cliente")
                        .WithMany("Vendas")
                        .HasForeignKey("ClienteId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Cliente");
                });

            modelBuilder.Entity("Financeiro.Domain.Entities.VendaItem", b =>
                {
                    b.HasOne("Financeiro.Domain.Entities.Produto", "Produto")
                        .WithMany("VendaItens")
                        .HasForeignKey("ProdutoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Financeiro.Domain.Entities.Venda", "Venda")
                        .WithMany("VendaItens")
                        .HasForeignKey("VendaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Produto");

                    b.Navigation("Venda");
                });

            modelBuilder.Entity("Financeiro.Domain.Entities.Cliente", b =>
                {
                    b.Navigation("Vendas");
                });

            modelBuilder.Entity("Financeiro.Domain.Entities.Produto", b =>
                {
                    b.Navigation("VendaItens");
                });

            modelBuilder.Entity("Financeiro.Domain.Entities.Venda", b =>
                {
                    b.Navigation("Pagamentos");

                    b.Navigation("VendaItens");
                });
#pragma warning restore 612, 618
        }
    }
}
