<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\Financeiro.Application\Financeiro.Application.csproj" />
    <ProjectReference Include="..\Financeiro.Domain\Financeiro.Domain.csproj" />
    <ProjectReference Include="..\Financeiro.Infra.Data\Financeiro.Infra.Data.csproj" />
  </ItemGroup>

</Project>
